// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAZJ5ZoYdwBu4nXpRsihPg4WYu5DIfnyg',
    appId: '1:157965399777:web:a63cd6c753ebb5778769a0',
    messagingSenderId: '157965399777',
    projectId: 'eatseesee-249dd',
    authDomain: 'eatseesee-249dd.firebaseapp.com',
    storageBucket: 'eatseesee-249dd.firebasestorage.app',
    measurementId: 'G-WKW5KH8DXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ2733hlhaZxdKcWSbsCmOpB9cigvwzEk',
    appId: '1:157965399777:android:3197428ccbc03c608769a0',
    messagingSenderId: '157965399777',
    projectId: 'eatseesee-249dd',
    storageBucket: 'eatseesee-249dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtBVGOwCCzbsHB6ItDSz0QfhrnSj1VQFI',
    appId: '1:157965399777:ios:690fdf55afaf9fa78769a0',
    messagingSenderId: '157965399777',
    projectId: 'eatseesee-249dd',
    storageBucket: 'eatseesee-249dd.firebasestorage.app',
    iosBundleId: 'com.example.chikankan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtBVGOwCCzbsHB6ItDSz0QfhrnSj1VQFI',
    appId: '1:157965399777:ios:690fdf55afaf9fa78769a0',
    messagingSenderId: '157965399777',
    projectId: 'eatseesee-249dd',
    storageBucket: 'eatseesee-249dd.firebasestorage.app',
    iosBundleId: 'com.example.chikankan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAZJ5ZoYdwBu4nXpRsihPg4WYu5DIfnyg',
    appId: '1:157965399777:web:b5eb33ae0dcce00e8769a0',
    messagingSenderId: '157965399777',
    projectId: 'eatseesee-249dd',
    authDomain: 'eatseesee-249dd.firebaseapp.com',
    storageBucket: 'eatseesee-249dd.firebasestorage.app',
    measurementId: 'G-MS3W0CR27Y',
  );
}
