import 'package:chikankan/View/sellers/seller_main.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'firebase_options.dart'; // This is auto-generated by FlutterFire
import 'package:chikankan/Controller/mnb_classifier.dart';
import 'package:chikankan/locator.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:chikankan/Controller/user_auth.dart';
import 'package:chikankan/View/customers/customer_homepage.dart';
import 'package:chikankan/View/customers/customer_login_page.dart';
import 'package:chikankan/View/customers/customer_signup_page.dart';
import 'package:chikankan/View/sellers/seller_login_page.dart';
import 'package:chikankan/View/sellers/seller_register_page.dart';
import 'package:chikankan/View/sellers/seller_verification.dart';
import 'package:chikankan/View/select_user_type_page.dart';
import 'package:huawei_location/huawei_location.dart';
import 'View/customers/customer_cart.dart';
import 'View/customers/customer_chat.dart';
import 'View/customers/customer_order.dart';
import 'View/customers/customer_profile.dart';
import 'View/customers/customer_tab.dart';


void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  
  setupLocator();
  await dotenv.load(fileName: ".env");
  //Initialize Naive Bayes Classifier
  await locator<NaiveBayesClassifier>().loadModel();
  
  //Initialize Huawei Location Service
  await locator<FusedLocationProviderClient>().initFusedLocationService();

  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    // Get AuthService instance from your locator
    final AuthService authService = locator<AuthService>();

    return MaterialApp(
      debugShowCheckedModeBanner: false,

      // --- Use StreamBuilder to determine the initial screen ---
      home: StreamBuilder<User?>(
        stream: authService.authStateChanges, // Listen to login state
        builder: (context, snapshot) {
          // Show loading indicator while checking auth state
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Scaffold(
              body: Center(child: CircularProgressIndicator()),
            );
          }
          
          if (snapshot.hasData && snapshot.data != null) {
            final User user = snapshot.data!; // Get the logged-in user
            print("User logged in: ${user.uid}");
            return FutureBuilder<AuthStatus?>(
              // Call the method from your AuthService to get role/status
              future: authService.getUserAuthStatus(user.uid), 
              builder: (context, authStatusSnapshot) {
            if (authStatusSnapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(body: Center(child: CircularProgressIndicator())); 
        }

        if (authStatusSnapshot.hasError) {
          print("Error checking user role: ${authStatusSnapshot.error}");
          // Show an error page or redirect to login (safer)
          return const SelectUserTypePage(); // Or a dedicated error screen
        }
        // --- Role check complete ---
        final AuthStatus? authStatus = authStatusSnapshot.data;

        if (authStatus != null) {
          // --- User Role Found ---
          if (authStatus.role == UserRole.customer) {
            print("User is a Customer. Navigating to CustomerTab.");
            return const CustomerTab(); // Navigate Customer
          } 
          else if (authStatus.role == UserRole.seller) {
            // Check if seller is verified
            if (authStatus.isVerified == true) {
              print("User is a Verified Seller. Navigating to SellerHomepage.");
              return const SellerMain(); // Navigate Verified Seller 
            } else {
              print("User is an Unverified Seller. Navigating to SellerVerification.");
              // Seller exists but is not verified
              return const SellerVerification(); // Navigate Unverified Seller
            }
          }
        } 
        
        // --- User Role NOT Found in Firestore (Error Case) ---
        print("User role not found in Firestore for UID: ${user.uid}. Logging out.");
        // Log the user out to prevent being stuck
        authService.signOut(); 
        return const SelectUserTypePage(); // Send back to login/selection
      },
    ); // End FutureBuilder for AuthStatus
  } 
  else {
    print("User is logged out.");
    return const SelectUserTypePage();
  }
        },
      ),

      // Keep your routes for named navigation
      routes: {
        '/select_user': (context) => const SelectUserTypePage(), // Add if needed
        '/seller_login': (context) => const SellerLoginPage(),
        '/seller_verification': (context) => const SellerVerification(),
        '/seller_register': (context) => const SellerRegisterPage(),
        '/seller_main': (context) => const SellerMain(),
        '/customer_login': (context) => const CustomerLoginPage(),
        '/customer_signup': (context) => const CustomerSignUpPage(),
        '/customer_tab': (context) => const CustomerTab(),
        '/customer_homepage': (context) => const CustomerHomepage(),
        '/customer_chat': (context) => const CustomerChat(),
        '/customer_cart': (context) => const CustomerCart(),
        '/customer_order': (context) => const CustomerOrder(),
        '/customer_profile': (context) => const CustomerProfile(),
      },
    );
  }
}
