import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This is auto-generated by FlutterFire
import 'package:chikankan/Controller/mnb_classifier.dart';
import 'package:chikankan/locator.dart';

import 'package:chikankan/View/customer_homepage.dart';
import 'package:chikankan/View/seller_homepage.dart';
import 'package:chikankan/View/seller_verification.dart';
import 'package:chikankan/View/select_user_type_page.dart';
import 'package:chikankan/View/seller_login_page.dart';
import 'package:chikankan/View/customer_login_page.dart';
import 'package:chikankan/View/seller_register_page.dart';
import 'package:chikankan/View/customer_signup_page.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  setupLocator();
  await locator<NaiveBayesClassifier>().loadModel();
  
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'ChiKanKan',
      initialRoute: '/',
      routes: {
        '/': (context) => const SelectUserTypePage(),
        '/seller_login': (context) => const SellerLoginPage(),
        '/customer_login': (context) => const CustomerLoginPage(),
        '/seller_homepage': (context) => const SellerHomepage(),
        '/customer_homepage': (context) => const CustomerHomepage(),
        '/seller_register': (context) => const SellerRegisterPage(),
        '/customer_signup': (context) => const CustomerSignUpPage(),
        '/seller_verification': (context) => const SellerVerification(),
      },
    );
  }
}
