import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This is auto-generated by FlutterFire
import 'package:chikankan/Controller/mnb_classifier.dart';
import 'package:chikankan/locator.dart';


import 'package:chikankan/View/customers/customer_homepage.dart';
import 'package:chikankan/View/customers/customer_login_page.dart';
import 'package:chikankan/View/customers/customer_signup_page.dart';
import 'package:chikankan/View/sellers/seller_homepage.dart';
import 'package:chikankan/View/sellers/seller_login_page.dart';
import 'package:chikankan/View/sellers/seller_register_page.dart';
import 'package:chikankan/View/sellers/seller_verification.dart';
import 'package:chikankan/View/select_user_type_page.dart';
import 'package:huawei_location/huawei_location.dart';
import 'View/customers/customer_cart.dart';
import 'View/customers/customer_chat.dart';
import 'View/customers/customer_order.dart';
import 'View/customers/customer_profile.dart';
import 'View/customers/customer_tab.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  setupLocator();
  await locator<NaiveBayesClassifier>().loadModel();
  
  await locator<FusedLocationProviderClient>().initFusedLocationService();
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'ChiKanKan',
      initialRoute: '/',
      routes: {
        '/': (context) => const SelectUserTypePage(),
        '/seller_login': (context) => const SellerLoginPage(),
        '/seller_verification': (context) => const SellerVerification(),
        '/seller_register': (context) => const SellerRegisterPage(),
        '/seller_homepage': (context) => const SellerHomepage(),

        '/customer_login': (context) => const CustomerLoginPage(),
        '/customer_signup': (context) => const CustomerSignUpPage(),   
        '/customer_tab': (context) => const CustomerTab(),     
        '/customer_homepage': (context) => const CustomerHomepage(),
        '/customer_chat': (context) => const CustomerChat(),
        '/customer_cart': (context) => const CustomerCart(),
        '/customer_order': (context) => const CustomerOrder(),
        '/customer_profile': (context) => const CustomerProfile(),
        
        
      },
    );
  }
}
